---
- name: Install global build dependencies
  ansible.builtin.apt:
    name: "{{ build_dependencies }}"
    state: present
    install_recommends: no
  become: yes

# - name: Autoremove unneeded packages
#   ansible.builtin.apt:
#     autoremove: yes

# - name: Clean apt package cache
#   ansible.builtin.apt:
#     clean: yes