---
- name: Clone fzf repository
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: /opt/tools/fzf
    depth: 1
  become: yes

- name: Run fzf install script
  ansible.builtin.command:
    cmd: /opt/tools/fzf/install
  args:
    creates: /opt/tools/fzf/bin/fzf
  become: yes

- name: Configure fzf environment
  ansible.builtin.copy:
    dest: "{{ target_user_home }}/.zshrc.d/20-fzf.zsh"
    content: |
      # fzf
      export FZF_BASE=/opt/tools/fzf
      [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    mode: '0644'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Create fzf aliases
  ansible.builtin.copy:
    dest: "{{ target_user_home }}/.zsh_aliases.d/fzf.zsh"
    content: |
      # FZF Aliases
      alias fzf-wordlists='find /opt/lists /usr/share/wordlists /usr/share/wfuzz /usr/share/dirb -type f | fzf'
      alias fzf-rules='find /opt/rules/ /usr/share/hashcat/rules/ -type f | fzf'
      alias fzf-haiti-hashcat='(){ haiti -e $1 | fzf --ansi | grep -E -o " [0-9]*]" | cut -d "]" -f 1 | cut -d " " -f 2 ;}'
      alias fzf-haiti-john='(){ haiti -e $1 | fzf --ansi | grep -E -o "JtR: .*]" | cut -d "]" -f 1 | cut -d " " -f 2 ;}'
      alias hcat='(){ if [ -f "$1" ]; then hashcat -m $(fzf-haiti-hashcat $(head -n 1 "$1")) "$1" $(fzf-wordlists) "${@:2}"; elif [ -n "$1" ]; then hashcat -m $(fzf-haiti-hashcat "$1") "$1" $(fzf-wordlists) "${@:2}"; fi ;}'
      alias hjohn='(){ if [ -f "$1" ]; then john --format=$(fzf-haiti-john $(head -n 1 "$1")) --wordlist=$(fzf-wordlists) "${@:2}" $1; elif [ -n "$1" ]; then echo "$1" | john --format=$(fzf-haiti-john "$1") --wordlist=$(fzf-wordlists) "${@:2}" /dev/stdin; fi ;}'
    mode: '0644'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"