---
# - name: (VM) Update apt cache
#   ansible.builtin.apt:
#     update_cache: yes
#   changed_when: false

# - name: (VM) Perform a distribution upgrade
#   ansible.builtin.apt:
#     upgrade: dist

- name: (VM) Install common VM packages
  ansible.builtin.apt:
    name: "{{ common_vm_packages }}"
    state: present

- name: (VM) Autoremove unneeded packages
  ansible.builtin.apt:
    autoremove: yes